create type action_enum as enum ('P', 'E', 'C');

CREATE TABLE if not exists event_action (
	id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	action  action_enum                        NOT NULL,
	event_can VARCHAR(255)                            NOT NULL,
	CONSTRAINT pk_eventaction PRIMARY KEY (id)
);

CREATE INDEX actionIdx ON event_action(action);