name: build_and_deploy
on:
  push:
    branches:
      - main

jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest

    container: postgres
    services:
      postgres:
        image: 'postgres:latest'
        env:
          POSTGRES_DB: ${{ vars.MODULITH_DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.MODULITH_PASSWORD }}
          POSTGRES_USER: ${{ secrets.MODULITH_USERNAME }}
        ports:
          - 5432:5432

    steps:
      - name: Pull Code
        uses: actions/checkout@v4
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: run maven test
        env:
          SPRING_PROFILES_ACTIVE: ${{ vars.SPRING_PROFILES_ACTIVE }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MODULITH_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MODULITH_PASSWORD }}
          DELETE_EVENT_DURATION: 4000
          ACTUATOR_EXPOSED_ENDPOINTS: ${{ vars.ACTUATOR_EXPOSED_ENDPOINTS }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          MODULITH_USERNAME: ${{ secrets.MODULITH_USERNAME }}
          MODULITH_PASSWORD: ${{ secrets.MODULITH_PASSWORD }}
          MODULITH_HOST: ${{ vars.MODULITH_HOST }}
          MODULITH_PORT: ${{ vars.MODULITH_PORT }}
          MODULITH_DB_NAME: ${{ vars.MODULITH_DB_NAME }}
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dspring-boot.run.profiles=${{ vars.SPRING_PROFILES_ACTIVE }}
